interpreter:
  languages:
    python:
      cmd: /usr/bin/python
      fileExtension: py
      inlineOption: -c
    bash:
      cmd: bash
      fileExtension: sh
      inlineOption: -c
    javascript:
      cmd: /usr/local/bin/node
      fileExtension: js
      inlineOption: -e

server:
  session:
    timeout: 5
