interpreter:
  languages:
    python:
      cmd: /usr/bin/python
      fileExtension: py
      inlineOption: -c
    bash:
      cmd: bash
      fileExtension: sh
      inlineOption: -c

server:
  session:
    timeout: 5
